version: '3.8'
name: spring-boot-3-jre-21-demo

services:
  spring-boot-3-jre-21-demo:
    image: ghcr.io/mrgraversen/spring-boot-3-jre-21-demo
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    restart: unless-stopped